### PR TITLE
Core/Quests: Fix autocomplete quests on UI

### PR DESCRIPTION
**Pull request by slash-design**

### CODE REVIEW

**Comment by jasongdove** [comment]
I'm trying to repro this build error that I get locally so we can let github check for us automatically... I might also have to add a clang action? I guess that's what I'm using locally.

> QuestHandler.cpp:492:100: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]

**Comment by slash-design** [comment]
Mate, that could be my fault...
can u pls try this line that way??

TC_LOG_DEBUG("network", "WORLD: Received CMSG_QUESTGIVER_REQUEST_REWARD npc = %s, quest = %u", packet.QuestGiverGUID.ToString().c_str(), packet.QuestID);

**Comment by jasongdove** [comment]
Yeah, I understand the old vs new logging is the cause of the build error. I just want github to show the PR as having failed a check in this state. Once I get that working, we can change the logging style and get this merged.

**Comment by jasongdove** [comment]
There we go - the PR shows a failing build. Now I'll update the logging.

**Comment by slash-design** [comment]
yeah Mate, you've got it :-)

**Pull request merged**
